name: Bug Report
description: File a bug report to help us improve
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us resolve the issue quickly.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Paste screenshots here...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Frontend (React/Next.js)
        - Backend (Node.js/Express)
        - Database (PostgreSQL)
        - Authentication
        - Video Consultation
        - Email System
        - Crisis Detection
        - Analytics Dashboard
        - Infrastructure/Deployment
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - System unusable
        - High - Major feature broken
        - Medium - Minor feature broken
        - Low - Cosmetic issue
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      placeholder: e.g. Chrome 120, Firefox 121, Safari 17

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which OS are you using?
      placeholder: e.g. Windows 11, macOS 14, Ubuntu 22.04

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Any relevant environment information
      placeholder: |
        - Node.js version:
        - Docker version:
        - Database version:
        - Other relevant details:

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please provide any relevant log outputs
      placeholder: Paste logs here (remove any sensitive information)

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues before creating this one
          required: true
        - label: I have provided all the requested information
          required: true
        - label: This issue does not contain sensitive information (passwords, API keys, etc.)
          required: true