name: Feature Request
description: Suggest an idea for the Neurona platform
title: "[FEATURE] "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature for Neurona! Please provide detailed information about your idea.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see
      placeholder: Provide a concise summary of the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the platform would this feature affect?
      options:
        - Frontend (Patient Interface)
        - Frontend (Doctor Dashboard)
        - Frontend (Admin Dashboard)
        - Backend (API)
        - Database
        - Authentication & Security
        - Video Consultation
        - Email & Notifications
        - Crisis Detection & Management
        - Analytics & Reporting
        - Mobile App
        - Infrastructure
        - Other
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: User Type
      description: Who would benefit from this feature?
      options:
        - Patients
        - Healthcare Providers (Doctors)
        - Administrators
        - System Administrators
        - All Users
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical - Blocking current workflow
        - High - Would significantly improve user experience
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific use cases for this feature
      placeholder: |
        1. As a [user type], I want to [action] so that [benefit]
        2. As a [user type], I want to [action] so that [benefit]

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What conditions must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Wireframes
      description: If you have any visual representations of the feature, please share them
      placeholder: Paste images or links to mockups/wireframes here...

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Any technical aspects to consider (security, performance, compatibility, etc.)
      placeholder: |
        - Security implications:
        - Performance considerations:
        - Integration requirements:
        - Compliance requirements (HIPAA, etc.):

  - type: textarea
    id: business-value
    attributes:
      label: Business Value
      description: What business value would this feature provide?
      placeholder: |
        - Improved patient outcomes
        - Increased provider efficiency
        - Better compliance
        - Cost reduction
        - Other benefits

  - type: input
    id: timeline
    attributes:
      label: Desired Timeline
      description: When would you like to see this feature implemented?
      placeholder: e.g., Q2 2024, ASAP, No rush

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, research, or examples about the feature request here

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests before creating this one
          required: true
        - label: This feature aligns with Neurona's mission of improving mental healthcare
          required: true
        - label: I understand this is a request and not a guarantee of implementation
          required: true